name: Application CI
env:
  JFROG_ARTIFACTORY: urmilag.jfrog.io/docker-local
  JFROG_ARTIFACTORY_BUCKET: docker-local

on:
  push:
    branches: [ develop, master, jfrog-sessionkey ]
  pull_request:
    branches: [ develop, master ]


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      if: ${{ success() }}
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx --no-restore --verbosity normal
    
    - name: Generate report
      if: ${{ success() }}
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool 
        ~/.dotnet/tools/reportgenerator "-reports:./TimeManagementUT/coverage.opencover.xml" "-targetdir:./CodeCoverage" "-reporttypes:HtmlInline_AzurePipelines;Cobertura"
    
    - name: code analysis using sonar cloud
      if: ${{ success() }}
      run: |
        dotnet tool install --global dotnet-sonarscanner 
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx --no-restore --verbosity normal
        dotnet build-server shutdown
        dotnet sonarscanner begin /k:${{ secrets.SONAR_PROJECT_KEY }} /o:${{ secrets.SONAR_ORG_KEY }} /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.cs.opencover.reportsPaths="./TimeManagementUT/coverage.opencover.xml" /d:sonar.cs.vstest.reportsPaths="./TimeManagementUT/TestResults/*.trx"
        dotnet build ./xunit_practice_two.sln
        dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  publish_docker_image:
    if: github.event_name == 'push' 
    runs-on: ubuntu-latest
    env:
      $CONTAINER_IMAGE: sample-app-${github_ref##*/}:${github_sha::8}
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image for develop
        run: |
          docker build . --file ./scripts/build/Dockerfile -t sample-app-${GITHUB_REF##*/}:${GITHUB_SHA::8}
          docker tag sample-app-${GITHUB_REF##*/}:${GITHUB_SHA::8} $JFROG_ARTIFACTORY/sample-app-${GITHUB_REF##*/}:${GITHUB_SHA::8}
      - name: Setup Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        with:
          VERSION: 1.39.2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_1 }}
      - name: ping to jfrog cli
        run: |
          jfrog rt ping
#      - run: |
#         jfrog rt ping
#          jfrog rt dp $JFROG_ARTIFACTORY/sample-app-${GITHUB_REF##*/}:${GITHUB_SHA::8} $JFROG_ARTIFACTORY_BUCKET 
 #         jfrog rt c artifactory --url=$JFROG_URL --user=$JFROG_USERNAME --apikey=$JFROG_API_KEY --enc-password=false
#          jfrog rt c artifactory --interactive=false --enc-password=true --url=$JFROG_URL --access-token=$JF_ARTIFACTORY_1
         
